/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedHousekeepingRouteImport } from './routes/_authenticated/housekeeping'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReceptionRouteImport } from './routes/_authenticated/reception'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as BookingReferenceRouteImport } from './routes/booking.$reference'
import { Route as HotelsSlugRouteImport } from './routes/hotels.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminDiscoveryRouteImport } from './routes/_admin/admin.discovery'
import { Route as AdminAdminHotelsRouteImport } from './routes/_admin/admin.hotels'
import { Route as AdminAdminPlansRouteImport } from './routes/_admin/admin.plans'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminTeamRouteImport } from './routes/_admin/admin.team'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHousekeepingRoute =
  AuthenticatedHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceptionRoute = AuthenticatedReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BookingReferenceRoute = BookingReferenceRouteImport.update({
  id: '/booking/$reference',
  path: '/booking/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSlugRoute = HotelsSlugRouteImport.update({
  id: '/hotels/$slug',
  path: '/hotels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDiscoveryRoute = AdminAdminDiscoveryRouteImport.update({
  id: '/admin/discovery',
  path: '/admin/discovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminHotelsRoute = AdminAdminHotelsRouteImport.update({
  id: '/admin/hotels',
  path: '/admin/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlansRoute = AdminAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTeamRoute = AdminAdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/admin/discovery': typeof AdminAdminDiscoveryRoute
  '/admin/hotels': typeof AdminAdminHotelsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/admin/discovery': typeof AdminAdminDiscoveryRoute
  '/admin/hotels': typeof AdminAdminHotelsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin': typeof AdminAdminIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reception': typeof AuthenticatedReceptionRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/_admin/admin/discovery': typeof AdminAdminDiscoveryRoute
  '/_admin/admin/hotels': typeof AdminAdminHotelsRoute
  '/_admin/admin/plans': typeof AdminAdminPlansRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/team': typeof AdminAdminTeamRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/register'
    | '/dashboard'
    | '/guests'
    | '/housekeeping'
    | '/onboarding'
    | '/payments'
    | '/reception'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/booking/$reference'
    | '/hotels/$slug'
    | '/admin/discovery'
    | '/admin/hotels'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/bookings/$id'
    | '/api/public/paystack-webhook'
    | '/admin/'
    | '/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/register'
    | '/dashboard'
    | '/guests'
    | '/housekeeping'
    | '/onboarding'
    | '/payments'
    | '/reception'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/booking/$reference'
    | '/hotels/$slug'
    | '/admin/discovery'
    | '/admin/hotels'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/bookings/$id'
    | '/api/public/paystack-webhook'
    | '/admin'
    | '/bookings'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/guests'
    | '/_authenticated/housekeeping'
    | '/_authenticated/onboarding'
    | '/_authenticated/payments'
    | '/_authenticated/reception'
    | '/_authenticated/rooms'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/booking/$reference'
    | '/hotels/$slug'
    | '/_admin/admin/discovery'
    | '/_admin/admin/hotels'
    | '/_admin/admin/plans'
    | '/_admin/admin/settings'
    | '/_admin/admin/team'
    | '/_admin/admin/users'
    | '/_authenticated/bookings/$id'
    | '/api/public/paystack-webhook'
    | '/_admin/admin/'
    | '/_authenticated/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  RegisterRoute: typeof RegisterRoute
  BookingReferenceRoute: typeof BookingReferenceRoute
  HotelsSlugRoute: typeof HotelsSlugRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/housekeeping': {
      id: '/_authenticated/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AuthenticatedHousekeepingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/booking/$reference': {
      id: '/booking/$reference'
      path: '/booking/$reference'
      fullPath: '/booking/$reference'
      preLoaderRoute: typeof BookingReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$slug': {
      id: '/hotels/$slug'
      path: '/hotels/$slug'
      fullPath: '/hotels/$slug'
      preLoaderRoute: typeof HotelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/discovery': {
      id: '/_admin/admin/discovery'
      path: '/admin/discovery'
      fullPath: '/admin/discovery'
      preLoaderRoute: typeof AdminAdminDiscoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/hotels': {
      id: '/_admin/admin/hotels'
      path: '/admin/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminAdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/plans': {
      id: '/_admin/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminAdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/team': {
      id: '/_admin/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDiscoveryRoute: typeof AdminAdminDiscoveryRoute
  AdminAdminHotelsRoute: typeof AdminAdminHotelsRoute
  AdminAdminPlansRoute: typeof AdminAdminPlansRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminTeamRoute: typeof AdminAdminTeamRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDiscoveryRoute: AdminAdminDiscoveryRoute,
  AdminAdminHotelsRoute: AdminAdminHotelsRoute,
  AdminAdminPlansRoute: AdminAdminPlansRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminTeamRoute: AdminAdminTeamRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedHousekeepingRoute: typeof AuthenticatedHousekeepingRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReceptionRoute: typeof AuthenticatedReceptionRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedHousekeepingRoute: AuthenticatedHousekeepingRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReceptionRoute: AuthenticatedReceptionRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  RegisterRoute: RegisterRoute,
  BookingReferenceRoute: BookingReferenceRoute,
  HotelsSlugRoute: HotelsSlugRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
