/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelSlugRouteImport } from './routes/$hotelSlug'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SchoolRouteImport } from './routes/_school'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAllocationsRouteImport } from './routes/_authenticated/allocations'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedHousekeepingRouteImport } from './routes/_authenticated/housekeeping'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReceptionRouteImport } from './routes/_authenticated/reception'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as BookingReferenceRouteImport } from './routes/booking.$reference'
import { Route as HotelsSlugRouteImport } from './routes/hotels.$slug'
import { Route as InvitesIdRouteImport } from './routes/invites.$id'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminDiscoveryRouteImport } from './routes/_admin/admin.discovery'
import { Route as AdminAdminHotelsRouteImport } from './routes/_admin/admin.hotels'
import { Route as AdminAdminPlansRouteImport } from './routes/_admin/admin.plans'
import { Route as AdminAdminRequestsRouteImport } from './routes/_admin/admin.requests'
import { Route as AdminAdminSchoolsRouteImport } from './routes/_admin/admin.schools'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminTeamRouteImport } from './routes/_admin/admin.team'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as SchoolSchoolIndexRouteImport } from './routes/_school/school.index'
import { Route as SchoolSchoolHostelsRouteImport } from './routes/_school/school.hostels'
import { Route as SchoolSchoolSettingsRouteImport } from './routes/_school/school.settings'
import { Route as SchoolSchoolStudentsRouteImport } from './routes/_school/school.students'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as SchoolSchoolRequestsIndexRouteImport } from './routes/_school/school.requests.index'
import { Route as SchoolSchoolRequestsIdRouteImport } from './routes/_school/school.requests.$id'
import { Route as ApiPublicIcalTokenRouteImport } from './routes/api/public/ical.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelSlugRoute = HotelSlugRouteImport.update({
  id: '/$hotelSlug',
  path: '/$hotelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/_school',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAllocationsRoute =
  AuthenticatedAllocationsRouteImport.update({
    id: '/allocations',
    path: '/allocations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHousekeepingRoute =
  AuthenticatedHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceptionRoute = AuthenticatedReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BookingReferenceRoute = BookingReferenceRouteImport.update({
  id: '/booking/$reference',
  path: '/booking/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSlugRoute = HotelsSlugRouteImport.update({
  id: '/hotels/$slug',
  path: '/hotels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesIdRoute = InvitesIdRouteImport.update({
  id: '/invites/$id',
  path: '/invites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDiscoveryRoute = AdminAdminDiscoveryRouteImport.update({
  id: '/admin/discovery',
  path: '/admin/discovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminHotelsRoute = AdminAdminHotelsRouteImport.update({
  id: '/admin/hotels',
  path: '/admin/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlansRoute = AdminAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRequestsRoute = AdminAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSchoolsRoute = AdminAdminSchoolsRouteImport.update({
  id: '/admin/schools',
  path: '/admin/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTeamRoute = AdminAdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SchoolSchoolIndexRoute = SchoolSchoolIndexRouteImport.update({
  id: '/school/',
  path: '/school/',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolSchoolHostelsRoute = SchoolSchoolHostelsRouteImport.update({
  id: '/school/hostels',
  path: '/school/hostels',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolSchoolSettingsRoute = SchoolSchoolSettingsRouteImport.update({
  id: '/school/settings',
  path: '/school/settings',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolSchoolStudentsRoute = SchoolSchoolStudentsRouteImport.update({
  id: '/school/students',
  path: '/school/students',
  getParentRoute: () => SchoolRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const SchoolSchoolRequestsIndexRoute =
  SchoolSchoolRequestsIndexRouteImport.update({
    id: '/school/requests/',
    path: '/school/requests/',
    getParentRoute: () => SchoolRoute,
  } as any)
const SchoolSchoolRequestsIdRoute = SchoolSchoolRequestsIdRouteImport.update({
  id: '/school/requests/$id',
  path: '/school/requests/$id',
  getParentRoute: () => SchoolRoute,
} as any)
const ApiPublicIcalTokenRoute = ApiPublicIcalTokenRouteImport.update({
  id: '/api/public/ical/$token',
  path: '/api/public/ical/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$hotelSlug': typeof HotelSlugRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/register': typeof RegisterRoute
  '/allocations': typeof AuthenticatedAllocationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/invites/$id': typeof InvitesIdRoute
  '/admin/discovery': typeof AdminAdminDiscoveryRoute
  '/admin/hotels': typeof AdminAdminHotelsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/schools': typeof AdminAdminSchoolsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/school/hostels': typeof SchoolSchoolHostelsRoute
  '/school/settings': typeof SchoolSchoolSettingsRoute
  '/school/students': typeof SchoolSchoolStudentsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/school/': typeof SchoolSchoolIndexRoute
  '/school/requests/$id': typeof SchoolSchoolRequestsIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
  '/school/requests/': typeof SchoolSchoolRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$hotelSlug': typeof HotelSlugRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/register': typeof RegisterRoute
  '/allocations': typeof AuthenticatedAllocationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reception': typeof AuthenticatedReceptionRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/invites/$id': typeof InvitesIdRoute
  '/admin/discovery': typeof AdminAdminDiscoveryRoute
  '/admin/hotels': typeof AdminAdminHotelsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/schools': typeof AdminAdminSchoolsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/school/hostels': typeof SchoolSchoolHostelsRoute
  '/school/settings': typeof SchoolSchoolSettingsRoute
  '/school/students': typeof SchoolSchoolStudentsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin': typeof AdminAdminIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/school': typeof SchoolSchoolIndexRoute
  '/school/requests/$id': typeof SchoolSchoolRequestsIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
  '/school/requests': typeof SchoolSchoolRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$hotelSlug': typeof HotelSlugRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_school': typeof SchoolRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/register': typeof RegisterRoute
  '/_authenticated/allocations': typeof AuthenticatedAllocationsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/housekeeping': typeof AuthenticatedHousekeepingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reception': typeof AuthenticatedReceptionRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/invites/$id': typeof InvitesIdRoute
  '/_admin/admin/discovery': typeof AdminAdminDiscoveryRoute
  '/_admin/admin/hotels': typeof AdminAdminHotelsRoute
  '/_admin/admin/plans': typeof AdminAdminPlansRoute
  '/_admin/admin/requests': typeof AdminAdminRequestsRoute
  '/_admin/admin/schools': typeof AdminAdminSchoolsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/team': typeof AdminAdminTeamRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_school/school/hostels': typeof SchoolSchoolHostelsRoute
  '/_school/school/settings': typeof SchoolSchoolSettingsRoute
  '/_school/school/students': typeof SchoolSchoolStudentsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_school/school/': typeof SchoolSchoolIndexRoute
  '/_school/school/requests/$id': typeof SchoolSchoolRequestsIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
  '/_school/school/requests/': typeof SchoolSchoolRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$hotelSlug'
    | '/auth'
    | '/discover'
    | '/register'
    | '/allocations'
    | '/billing'
    | '/calendar'
    | '/channels'
    | '/dashboard'
    | '/finance'
    | '/guests'
    | '/housekeeping'
    | '/onboarding'
    | '/payments'
    | '/reception'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/booking/$reference'
    | '/hotels/$slug'
    | '/invites/$id'
    | '/admin/discovery'
    | '/admin/hotels'
    | '/admin/plans'
    | '/admin/requests'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/bookings/$id'
    | '/school/hostels'
    | '/school/settings'
    | '/school/students'
    | '/api/public/paystack-webhook'
    | '/admin/'
    | '/bookings/'
    | '/school/'
    | '/school/requests/$id'
    | '/api/public/ical/$token'
    | '/school/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$hotelSlug'
    | '/auth'
    | '/discover'
    | '/register'
    | '/allocations'
    | '/billing'
    | '/calendar'
    | '/channels'
    | '/dashboard'
    | '/finance'
    | '/guests'
    | '/housekeeping'
    | '/onboarding'
    | '/payments'
    | '/reception'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/booking/$reference'
    | '/hotels/$slug'
    | '/invites/$id'
    | '/admin/discovery'
    | '/admin/hotels'
    | '/admin/plans'
    | '/admin/requests'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/bookings/$id'
    | '/school/hostels'
    | '/school/settings'
    | '/school/students'
    | '/api/public/paystack-webhook'
    | '/admin'
    | '/bookings'
    | '/school'
    | '/school/requests/$id'
    | '/api/public/ical/$token'
    | '/school/requests'
  id:
    | '__root__'
    | '/'
    | '/$hotelSlug'
    | '/_admin'
    | '/_authenticated'
    | '/_school'
    | '/auth'
    | '/discover'
    | '/register'
    | '/_authenticated/allocations'
    | '/_authenticated/billing'
    | '/_authenticated/calendar'
    | '/_authenticated/channels'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/guests'
    | '/_authenticated/housekeeping'
    | '/_authenticated/onboarding'
    | '/_authenticated/payments'
    | '/_authenticated/reception'
    | '/_authenticated/rooms'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/booking/$reference'
    | '/hotels/$slug'
    | '/invites/$id'
    | '/_admin/admin/discovery'
    | '/_admin/admin/hotels'
    | '/_admin/admin/plans'
    | '/_admin/admin/requests'
    | '/_admin/admin/schools'
    | '/_admin/admin/settings'
    | '/_admin/admin/team'
    | '/_admin/admin/users'
    | '/_authenticated/bookings/$id'
    | '/_school/school/hostels'
    | '/_school/school/settings'
    | '/_school/school/students'
    | '/api/public/paystack-webhook'
    | '/_admin/admin/'
    | '/_authenticated/bookings/'
    | '/_school/school/'
    | '/_school/school/requests/$id'
    | '/api/public/ical/$token'
    | '/_school/school/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelSlugRoute: typeof HotelSlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SchoolRoute: typeof SchoolRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  RegisterRoute: typeof RegisterRoute
  BookingReferenceRoute: typeof BookingReferenceRoute
  HotelsSlugRoute: typeof HotelsSlugRoute
  InvitesIdRoute: typeof InvitesIdRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicIcalTokenRoute: typeof ApiPublicIcalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$hotelSlug': {
      id: '/$hotelSlug'
      path: '/$hotelSlug'
      fullPath: '/$hotelSlug'
      preLoaderRoute: typeof HotelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_school': {
      id: '/_school'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/allocations': {
      id: '/_authenticated/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AuthenticatedAllocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/housekeeping': {
      id: '/_authenticated/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AuthenticatedHousekeepingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/booking/$reference': {
      id: '/booking/$reference'
      path: '/booking/$reference'
      fullPath: '/booking/$reference'
      preLoaderRoute: typeof BookingReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$slug': {
      id: '/hotels/$slug'
      path: '/hotels/$slug'
      fullPath: '/hotels/$slug'
      preLoaderRoute: typeof HotelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$id': {
      id: '/invites/$id'
      path: '/invites/$id'
      fullPath: '/invites/$id'
      preLoaderRoute: typeof InvitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/discovery': {
      id: '/_admin/admin/discovery'
      path: '/admin/discovery'
      fullPath: '/admin/discovery'
      preLoaderRoute: typeof AdminAdminDiscoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/hotels': {
      id: '/_admin/admin/hotels'
      path: '/admin/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminAdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/plans': {
      id: '/_admin/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminAdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/requests': {
      id: '/_admin/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminAdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/schools': {
      id: '/_admin/admin/schools'
      path: '/admin/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminAdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/team': {
      id: '/_admin/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_school/school/': {
      id: '/_school/school/'
      path: '/school'
      fullPath: '/school/'
      preLoaderRoute: typeof SchoolSchoolIndexRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/school/hostels': {
      id: '/_school/school/hostels'
      path: '/school/hostels'
      fullPath: '/school/hostels'
      preLoaderRoute: typeof SchoolSchoolHostelsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/school/settings': {
      id: '/_school/school/settings'
      path: '/school/settings'
      fullPath: '/school/settings'
      preLoaderRoute: typeof SchoolSchoolSettingsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/school/students': {
      id: '/_school/school/students'
      path: '/school/students'
      fullPath: '/school/students'
      preLoaderRoute: typeof SchoolSchoolStudentsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_school/school/requests/': {
      id: '/_school/school/requests/'
      path: '/school/requests'
      fullPath: '/school/requests/'
      preLoaderRoute: typeof SchoolSchoolRequestsIndexRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/_school/school/requests/$id': {
      id: '/_school/school/requests/$id'
      path: '/school/requests/$id'
      fullPath: '/school/requests/$id'
      preLoaderRoute: typeof SchoolSchoolRequestsIdRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/api/public/ical/$token': {
      id: '/api/public/ical/$token'
      path: '/api/public/ical/$token'
      fullPath: '/api/public/ical/$token'
      preLoaderRoute: typeof ApiPublicIcalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDiscoveryRoute: typeof AdminAdminDiscoveryRoute
  AdminAdminHotelsRoute: typeof AdminAdminHotelsRoute
  AdminAdminPlansRoute: typeof AdminAdminPlansRoute
  AdminAdminRequestsRoute: typeof AdminAdminRequestsRoute
  AdminAdminSchoolsRoute: typeof AdminAdminSchoolsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminTeamRoute: typeof AdminAdminTeamRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDiscoveryRoute: AdminAdminDiscoveryRoute,
  AdminAdminHotelsRoute: AdminAdminHotelsRoute,
  AdminAdminPlansRoute: AdminAdminPlansRoute,
  AdminAdminRequestsRoute: AdminAdminRequestsRoute,
  AdminAdminSchoolsRoute: AdminAdminSchoolsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminTeamRoute: AdminAdminTeamRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAllocationsRoute: typeof AuthenticatedAllocationsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedHousekeepingRoute: typeof AuthenticatedHousekeepingRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReceptionRoute: typeof AuthenticatedReceptionRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAllocationsRoute: AuthenticatedAllocationsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedHousekeepingRoute: AuthenticatedHousekeepingRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReceptionRoute: AuthenticatedReceptionRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SchoolRouteChildren {
  SchoolSchoolHostelsRoute: typeof SchoolSchoolHostelsRoute
  SchoolSchoolSettingsRoute: typeof SchoolSchoolSettingsRoute
  SchoolSchoolStudentsRoute: typeof SchoolSchoolStudentsRoute
  SchoolSchoolIndexRoute: typeof SchoolSchoolIndexRoute
  SchoolSchoolRequestsIdRoute: typeof SchoolSchoolRequestsIdRoute
  SchoolSchoolRequestsIndexRoute: typeof SchoolSchoolRequestsIndexRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolSchoolHostelsRoute: SchoolSchoolHostelsRoute,
  SchoolSchoolSettingsRoute: SchoolSchoolSettingsRoute,
  SchoolSchoolStudentsRoute: SchoolSchoolStudentsRoute,
  SchoolSchoolIndexRoute: SchoolSchoolIndexRoute,
  SchoolSchoolRequestsIdRoute: SchoolSchoolRequestsIdRoute,
  SchoolSchoolRequestsIndexRoute: SchoolSchoolRequestsIndexRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelSlugRoute: HotelSlugRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SchoolRoute: SchoolRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  RegisterRoute: RegisterRoute,
  BookingReferenceRoute: BookingReferenceRoute,
  HotelsSlugRoute: HotelsSlugRoute,
  InvitesIdRoute: InvitesIdRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicIcalTokenRoute: ApiPublicIcalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
